### Get all posts
GET http://localhost:3000/api/post
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzU5MzQ5NDIsImV4cCI6MTczNTk0MjE0Mn0.fjqW87Tw0URuOZyveQQRFqduzZO18Uis7KX5BMqS0H8

### Get post by id
GET http://localhost:3000/api/post/675073bc49f76c9c0a7ab99c
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzU5MzQ5NDIsImV4cCI6MTczNTk0MjE0Mn0.fjqW87Tw0URuOZyveQQRFqduzZO18Uis7KX5BMqS0H8

### Create post
POST http://localhost:3000/api/post
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzgzNjU3NDEsImV4cCI6MTczODM3Mjk0MX0.GAsgF-CCx8TReoYqLauqA3PkglQrdUKKUIbX3v9CTzs

{
    "title": "It ends with us",
    "review": "It Ends with Us is a romance novel by Colleen Hoover. It tells the story of Lily Bloom and her doomed romance with Ryle Kincaid. The novel is a standalone, but Hoover has stated that she is working on a sequel.",
    "owner": "679261928bc76fb86d7d9e2c",
    "rate": 5,
}

### Update post
PUT http://localhost:3000/api/post/675073bc49f76c9c0a7ab99c
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzU5MzQ5NDIsImV4cCI6MTczNTk0MjE0Mn0.fjqW87Tw0URuOZyveQQRFqduzZO18Uis7KX5BMqS0H8

{
    "title": "Post 1",
    "review": "updated Content!",
    "owner": "675016b349f76c9c0a7ab99a"
}

### Delete post
DELETE http://localhost:3000/api/post/679d5eb9830e7bc3d6a90d5e
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzgzNjU3NDEsImV4cCI6MTczODM3Mjk0MX0.GAsgF-CCx8TReoYqLauqA3PkglQrdUKKUIbX3v9CTzs

### Get post by sender
GET http://localhost:3000/api/post?sender=675016b349f76c9c0a7ab99a
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzU5MzQ5NDIsImV4cCI6MTczNTk0MjE0Mn0.fjqW87Tw0URuOZyveQQRFqduzZO18Uis7KX5BMqS0H8

### Get comment by id
GET http://localhost:3000/api/comment/6766baf03a9f5c7b26fc0aef
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzgzNjU3NDEsImV4cCI6MTczODM3Mjk0MX0.GAsgF-CCx8TReoYqLauqA3PkglQrdUKKUIbX3v9CTzs

### Get comments count by post id
GET http://localhost:3000/api/comment/post/679ce63d3be6c7a6edc125ef
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzkyNjE5MjhiYzc2ZmI4NmQ3ZDllMmMiLCJpYXQiOjE3MzgzMzU3ODIsImV4cCI6MTczODM0Mjk4Mn0.kQxU0LS2iH8Z-mWgSdOPCWTEzXvWUdlVzX4CVgP2xyc


### Create comment
POST http://localhost:3000/api/comment
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzgyNDI0MDIsImV4cCI6MTczODI0OTYwMn0.VNhARzvE72DWuX4Kt0D5_ocCeppobUnrk9Xw9IgTJSs

{
    "message": "what a wonderful book!",
    "userId": "6776dae4891a0a3c15d223b8",
    "postId": "679b7984f99a311c22ebca7a"
}

### Update comment
PUT http://localhost:3000/api/comment/6769b1895938d243f1752c5d
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzgzNjU3NDEsImV4cCI6MTczODM3Mjk0MX0.GAsgF-CCx8TReoYqLauqA3PkglQrdUKKUIbX3v9CTzs

{
    "message": "updated comment!"
}

### Get post's comments
GET http://localhost:3000/api/comment?post=675073bc49f76c9c0a7ab99c
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzgzNjU3NDEsImV4cCI6MTczODM3Mjk0MX0.GAsgF-CCx8TReoYqLauqA3PkglQrdUKKUIbX3v9CTzs

### Delete comment
DELETE http://localhost:3000/api/comment/6769b1b85938d243f1752c5f
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzgzNjU3NDEsImV4cCI6MTczODM3Mjk0MX0.GAsgF-CCx8TReoYqLauqA3PkglQrdUKKUIbX3v9CTzs


# Authentication

### Registration
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Aya",
    "email": "aya.colman@ac.il",
    "password": "1234"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "carmelbd78@gmail.com",
    "password": "1234"
}

### Logout
POST http://localhost:3000/api/auth/logout
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzU5OTc3MjF9._6IKmrZaj5bGlcX_k0YmqfKF7Dl-0A9ygiEUhFQnC5A


### refresh token
POST http://localhost:3000/api/auth/refreshToken
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzc4M2Q1MTkxNWI5ZDE1MTY0NWE1OWIiLCJpYXQiOjE3MzU5OTU3MDd9.GlaS80SW69OAxpLnQTvGhnXXZ3DLChvwWdS2tc4sElY


### Create like
POST http://localhost:3000/api/like
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzkyNjE5MjhiYzc2ZmI4NmQ3ZDllMmMiLCJpYXQiOjE3MzgzNTI2ODAsImV4cCI6MTczODM1OTg4MH0.YZ7O-Ouvp8eF41Ad--s8fZfLZx9kqmEymXW5vtcoOe8

{
    "userId": "679261928bc76fb86d7d9e2c",
    "postId": "679ce63d3be6c7a6edc125ef"
}


### Gemini request
GET http://localhost:3000/api/gemini
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzkyNjE5MjhiYzc2ZmI4NmQ3ZDllMmMiLCJpYXQiOjE3Mzg1MTY0MjQsImV4cCI6MTczODUyMzYyNH0.1jnH-RkzESF-CJv5uYFrvhGV0XyA0pPxAreCTCGdcmk

{
    "prompt": "Hello, how are you?"
}